AWSTemplateFormationVersion: 2010-09-09
Description: Crate an s3 bucket template

Parameters: 
  S3BucketName:
    Description: Name of s3 bucket 
    Type: String 
  Environment:
    Description: Name of the environment where the object is going to be created
    Type: String 
    AllowedValues:
     - dev
     - prod 
     - qa

  Resources: 
    mybucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${Environment}-${S3BucketName}