593654001025-chester67049AWSTemplateFormatVersion: 2010-09-09
Description: Crate an s3 bucket template

Parameters: 
  S3BucketName:
    Description: Name of s3 bucket 
    Type: String 
    Default: mys3
  # Environment:
  #   Description: Name of the environment where the object is going to be created
  #   Type: String 
  #   AllowedValues:
  #    - dev
  #    - prod 
  #    - qa

conditions:
  IspreferredRegion: !Equals [!Ref "AWS::Region", us-east-1]
    

Resources: 
  CliveBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
    BucketName: !If [IspreferredRegion, !Join ["-", [!Ref "AWS::AccountId", !Ref S3BucketName]], !Join ["-", [!Ref "AWS::Region", !Ref S3BucketName]]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256