AWSTemplateFormatVersion: 2010-09-09
Description: Crate an s3 bucket template

Parameters: 
  S3BucketName:
    Description: Name of s3 bucket 
    Type: String 
    Default: mys3
    

Resources: 
  CliveBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ["-",[AWS::AccountId", !Ref S3BucketName]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: "PublicRead"
      VersioningConfiguration:
        Status: Enabled
      
      